import type { EvidencePack } from "@/lib/domain/evidence-pack";

type PdfLine = {
  text: string;
  size?: number;
  bold?: boolean;
  gapBefore?: number;
};

const pageWidth = 595;
const pageHeight = 842;
const marginX = 50;
const topY = 790;
const bottomY = 58;
const maxPages = 3;

export function downloadEvidencePackPdf(pack: EvidencePack) {
  const exportPack = { ...pack, exportedAt: new Date().toISOString() };
  const pdf = buildEvidencePdf(exportPack);
  const blob = new Blob([pdf], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = evidencePdfFileName(exportPack);
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

export function evidencePdfFileName(pack: Pick<EvidencePack, "customerSlug" | "exportedAt">) {
  const date = (pack.exportedAt || new Date().toISOString()).slice(0, 10);
  return `beacon-evidence-${pack.customerSlug || "client"}-${date}.pdf`;
}

export function buildEvidencePdf(pack: EvidencePack) {
  const lines = buildEvidenceLines(pack);
  const pages = paginate(lines);
  return buildPdfDocument(pages);
}

function buildEvidenceLines(pack: EvidencePack): PdfLine[] {
  const lines: Array<PdfLine | undefined> = [
    { text: "Dyna Beacon Evidence Pack", size: 18, bold: true },
    { text: pack.kind === "draft" ? "Demo evidence - synthetic data" : "Trace evidence - synthetic data", size: 11 },
    { text: "", gapBefore: 6 },
    { text: `Customer: ${pack.customerName}`, bold: true },
    { text: `Prepared by: ${pack.rmName}${pack.rmRole ? ` (${pack.rmRole})` : ""}` },
    { text: `Reviewed by: ${pack.reviewerName ? `${pack.reviewerName}${pack.reviewerRole ? ` (${pack.reviewerRole})` : ""}` : "Not required for this output"}` },
    { text: `Exported: ${formatDateTime(pack.exportedAt)}` },
    pack.generatedAt ? { text: `Output generated: ${formatDateTime(pack.generatedAt)}` } : undefined,
    { text: "", gapBefore: 8 },
    section("Lifecycle Timeline"),
    ...pack.timeline.flatMap((item) => [
      {
        text: `${formatDateTime(item.timestamp)} | ${item.label} | ${item.actorName}${item.actorRole ? ` (${item.actorRole})` : ""}`,
        bold: true
      },
      item.note ? { text: `Note: ${item.note}` } : undefined
    ]),
    { text: "", gapBefore: 8 },
    section(pack.kind === "draft" ? "Final Draft" : "Prepared Output"),
    { text: `Channel: ${pack.channelLabel}${pack.formatLabel ? ` | Format: ${pack.formatLabel}` : ""}` },
    pack.subject ? { text: `Subject: ${pack.subject}`, bold: true } : undefined,
    ...paragraphLines(pack.body),
    { text: "", gapBefore: 8 },
    section("Governance Evidence"),
    { text: `Guard result: ${pack.governance.guardLabel}` },
    { text: `Approval path: ${pack.governance.approvalLabel}` },
    pack.governance.approvalChain.length > 0
      ? { text: `Review chain: ${pack.governance.approvalChain.join(" -> ")}` }
      : undefined,
    ...pack.governance.ruleChecks.map((item) => ({ text: `- ${item}` })),
    pack.governance.sourceRefs.length > 0 ? { text: "Source references:", bold: true } : undefined,
    ...pack.governance.sourceRefs.map((item) => ({ text: `- ${item}` })),
    { text: "", gapBefore: 8 },
    section("Disclaimer"),
    ...paragraphLines(
      "Generated by Dyna Beacon from synthetic demo data. AI support is for RM productivity and comprehension. Final suitability, eligibility, approval, and client-facing judgment remain institution-owned."
    ),
    pack.appendix.length > 0 ? { text: "", gapBefore: 8 } : undefined,
    pack.appendix.length > 0 ? section("Technical Appendix") : undefined,
    ...pack.appendix.map((item) => ({ text: `${item.label}: ${item.value}` })),
    { text: "Generated by Dyna Beacon", size: 10 }
  ];

  return lines.filter((line): line is PdfLine => Boolean(line)).map((line) => ({
    ...line,
    text: cleanPdfText(line.text)
  }));
}

function section(text: string): PdfLine {
  return { text, size: 14, bold: true, gapBefore: 3 };
}

function paragraphLines(value: string): PdfLine[] {
  return value
    .split(/\r?\n/)
    .flatMap((line) => line.trim() ? [{ text: line }] : [{ text: "" }]);
}

function paginate(lines: PdfLine[]) {
  const pages: PdfLine[][] = [[]];
  let y = topY;

  for (const line of expandWrappedLines(lines)) {
    const lineHeight = lineHeightFor(line);
    if (y - lineHeight < bottomY && pages.length < maxPages) {
      pages.push([]);
      y = topY;
    }
    if (pages.length === maxPages && y - lineHeight < bottomY) {
      const current = pages[pages.length - 1];
      current.push({ text: "Evidence continues in the application trace.", size: 10 });
      break;
    }
    pages[pages.length - 1].push(line);
    y -= lineHeight;
  }

  return pages;
}

function expandWrappedLines(lines: PdfLine[]) {
  const expanded: PdfLine[] = [];
  for (const line of lines) {
    if (line.gapBefore) {
      expanded.push({ text: "", size: line.gapBefore });
    }
    const width = line.size && line.size >= 14 ? 64 : 88;
    for (const wrapped of wrapPdfLine(line.text, width)) {
      expanded.push({ ...line, text: wrapped, gapBefore: undefined });
    }
  }
  return expanded;
}

function lineHeightFor(line: PdfLine) {
  const size = line.size ?? 11;
  if (!line.text) return Math.max(8, size);
  return Math.max(13, Math.round(size * 1.35));
}

function buildPdfDocument(pages: PdfLine[][]) {
  const pageCount = pages.length;
  const fontRegularId = 3 + pageCount * 2;
  const fontBoldId = fontRegularId + 1;
  const objects: string[] = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    `<< /Type /Pages /Kids ${pdfArray(Array.from({ length: pageCount }, (_, index) => `${3 + index * 2} 0 R`))} /Count ${pageCount} >>`
  ];

  pages.forEach((pageLines, index) => {
    const pageObjectId = 3 + index * 2;
    const contentObjectId = pageObjectId + 1;
    const stream = buildPageStream(pageLines, index + 1, pageCount);
    objects.push(
      `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pageWidth} ${pageHeight}] /Resources << /Font << /F1 ${fontRegularId} 0 R /F2 ${fontBoldId} 0 R >> >> /Contents ${contentObjectId} 0 R >>`,
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`
    );
  });

  objects.push(
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"
  );

  let body = "%PDF-1.4\n";
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(body.length);
    body += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefAt = body.length;
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  body += offsets.slice(1).map((offset) => `${offset.toString().padStart(10, "0")} 00000 n \n`).join("");
  body += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefAt}\n%%EOF`;
  return body;
}

function buildPageStream(lines: PdfLine[], pageNumber: number, pageCount: number) {
  const commands = ["BT"];
  let y = topY;
  for (const line of lines) {
    const size = line.size ?? 11;
    const font = line.bold ? "F2" : "F1";
    y -= line.gapBefore ?? 0;
    if (line.text) {
      commands.push(`/${font} ${size} Tf`);
      commands.push(`${marginX} ${y} Td`);
      commands.push(`(${escapePdfText(toPdfAscii(line.text))}) Tj`);
      commands.push(`${-marginX} ${-y} Td`);
    }
    y -= lineHeightFor(line);
  }
  commands.push("/F1 9 Tf");
  commands.push(`${marginX} 32 Td`);
  commands.push(`(Generated by Dyna Beacon | Page ${pageNumber} of ${pageCount}) Tj`);
  commands.push("ET");
  return commands.join("\n");
}

function wrapPdfLine(line: string, width: number) {
  if (!line) return [""];
  const words = line.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  words.forEach((word) => {
    const next = current ? `${current} ${word}` : word;
    if (next.length > width && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
  });
  if (current) lines.push(current);
  return lines;
}

function pdfArray(items: string[]) {
  return `[${items.join(" ")}]`;
}

function formatDateTime(value: string) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short",
    hour12: false
  }).format(date);
}

function cleanPdfText(value: string) {
  return value
    .replace(/\b[a-z]+_\d{3,}[\w-]*/gi, "customer record")
    .replace(/\b[\w-]+_run_[\w-]+\b/gi, "agent run")
    .replace(/\b(skill-direct|mock|runtime|backend|LocalJsonRepo|DemoFallback|agent-studio|open-agent)\b/gi, "processing detail")
    .replace(/\s+/g, " ")
    .trim();
}

function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function toPdfAscii(value: string) {
  return value.replace(/[^\x20-\x7E]/g, "?");
}
